models/models1.py
class Users:
    def __init__(self, nome, senha, admin = False):
         self.nome = nome
         self.senha = senha
         self.admin = admin

    def __repr__(self):
        return f"Users(nome={self.nome}, senha={self.senha}, admin={self.admin})"     

users = []

user_1 = Users("muborges", "12345", True)
users.append(user_1)
user_2 = Users("rafapi", "12345")
users.append(user_2)

models/produtos.py
class Produto:
    def __init__(self, id, nome, preco, img):
        self.id = id
        self.nome = nome
        self.preco = preco
        self.img = img

    def __repr__(self):
        return f"Produtos(id={self.id}, nome={self.nome}, preco={self.preco}, img={self.img})"      

produtos = [Produto(0, "AMD Radeon RX 7900 XT", 5500, "https://tpucdn.com/gpu-specs/images/c/3912-front.small.jpg"),
            Produto(1, "NVIDIA GeForce RTX 4090", 15000, "https://tpucdn.com/gpu-specs/images/c/3889-front.small.jpg")]

app.py
from flask import Flask, render_template, request, redirect, url_for, flash, session, abort
from controllers.controller1 import mode
from controllers.carrinho import prod

app = Flask(__name__)
app.secret_key = '9751a2bf696a9d8ff9a136d07173a9cbe5fe4996c50f576cca1f42c882b1c8f4'

rotas_publicas = ["users.pegar", "users.login", "users.index", "users.logout", "static"]
rotas_privadas = ["users.vip"]

app.register_blueprint(mode)
app.register_blueprint(prod)


@app.before_request
def request_info():
    rota = request.endpoint
    print(rota)
    print(session.get('user_type'))
    print('username')
    print(session)

    if rota in rotas_publicas or rota is None:
        if 'username' in session and rota == "user.pegar":
            return redirect(url_for('users.index'))
        return

    if rota in rotas_privadas:
        if 'username' not in session or session.get('user_type') != 'vip':
            print("entou")
            flash("Acesso negado. Você precisa ser um usuário VIP.", "erro")
            abort(403)

    if rota not in rotas_privadas and rota not in rotas_publicas and 'username' not in session:
        flash("Necessario ter sessão")
        abort(403)        

@app.after_request
def after_request(response):
    print("Executa depois da requisição")
    return response

@app.errorhandler(404)
def pageNotFound(e):
    print(e)
    return render_template("404.html"), 404

@app.errorhandler(403)
def pagewithoutaccess(e):
    return render_template("403.html"), 403

@app.errorhandler(500)
def servererror(e):
    return render_template("500.html"), 500

@app.errorhandler(Exception)
def generic(e):
    print(e)
    return render_template("generic.html"), 500

if __name__ == '__main__':
    app.run(debug=True)

controllers/carrinho.py
from flask import Blueprint, render_template, request, redirect, url_for, make_response, flash
from models.produtos import produtos  # Importações

prod = Blueprint('produtos', __name__)

@prod.route('/carrinho')
def carrinho():
    # Cria um dicionário para armazenar os produtos no carrinho com base nos cookies
    carrinho = {}
    for produto in produtos:
        quantidade = request.cookies.get(f'produto_{produto.id}', 0)

        if int(quantidade) > 0:
            total = produto.preco * int(quantidade)
            carrinho[produto.id] = {'nome': produto.nome, 'qntd': int(quantidade), 'total': total}

    return render_template('carrinho.html', produtos=produtos, carrinho=carrinho)

@prod.route('/carrinho/add', methods=['GET', 'POST'])
def add():
    if request.method == 'GET':
        produto_id = request.args.get('id')
    elif request.method == 'POST':
        produto_id = request.form.get('id')
    else:
        print("oxi")

    resp = make_response(redirect(url_for('produtos.carrinho')))
    cookie = request.cookies.get(f'produto_{produto_id}')

    
    # Incrementa a quantidade do produto no cookie
    if cookie:
        resp.set_cookie(f'produto_{produto_id}', str(int(cookie) + 1))
    else:
        resp.set_cookie(f'produto_{produto_id}', "1")
    
    return resp

@prod.route('/carrinho/del', methods=['GET'])
def delete():
    produto_id = request.args.get('id')
    resp = make_response(redirect(url_for('produtos.carrinho')))
    cookie = request.cookies.get(f'produto_{produto_id}')
    
    # Decrementa a quantidade ou remove o cookie
    if cookie:
        if int(cookie) - 1 > 0:
            resp.set_cookie(f'produto_{produto_id}', str(int(cookie) - 1))
        else:
            resp.set_cookie(f'produto_{produto_id}', '', expires=0)  # Remove o cookie
    
    return resp

controllers/controller1.py
from flask import Blueprint, render_template, session, request, url_for, redirect, flash, abort
from models.models1 import users   # Importações

mode = Blueprint('users', __name__)  # Blueprint

@mode.route('/')  # Rota principal
def index():
    if 'username' in session:
        print(f"Bem Vindo {session['username']}")
        return render_template('html.html', users=users)
    return redirect(url_for('users.login'))

@mode.route('/login')   # Rota de login
def login():
    if 'username' in session:
        return redirect(url_for('users.index'))
    else:
        flash("Sem sessão", "erro")
        return redirect(url_for('users.pegar'))

@mode.route('/pegar', methods=['POST', 'GET'])   # Rota para obter dados
def pegar():
    if request.method == 'POST':
        nome = request.form.get('username')
        senha = request.form.get('password')

        # Verifica se o usuário e a senha estão corretos
        for user in users:
            if user.nome == nome and user.senha == senha:
                session['username'] = nome
                session['user_type'] = 'vip' if user.admin else 'publico'
                return redirect(url_for('users.index'))
            
        flash("Erro no login", "erro")
        return redirect(url_for('users.pegar'))

    # Se o método for GET, não há necessidade de verificar as credenciais aqui
    return render_template('login.html', aviso=False)

@mode.route('/vip')
def vip():
    return render_template('rotavip.html')

@mode.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('users.index'))

templates/carrinho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carrinho de Compras</title>
</head>
<body>
    <h1>Lista de Produtos</h1>
    <table>
        <thead>
            <tr>
                <th>Imagem</th>
                <th>Nome do Produto</th>
                <th>Preço</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for produto in produtos %}
                <tr>
                    <td><img src="{{ produto.img }}" alt="{{ produto.nome }}" width="100"></td> <!-- Corrigido para produto.img -->
                    <td>{{ produto.nome }}</td>
                    <td>R$ {{ produto.preco }}</td>
                    <td>
                        <a href="{{ url_for('produtos.add', id=produto.id) }}" class="botao">Adicionar</a> <!-- Corrigido de "Adicionr" para "Adicionar" -->
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <h1>Carrinho</h1>
    <ul>
        {% for id, produto in carrinho.items() %}
            <li>
                {{ produto.qntd }}x {{ produto.nome }}: R$ {{ produto.total }} <br>
                <a href="{{ url_for('produtos.delete', id=id) }}">Remover</a>
            </li>
        {% endfor %}
    </ul>
    
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
        <h1>Avisos</h1>
        <ul>
            {% for category, message in messages %}
            <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
</body>
</html>

templates/generic.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Erro Inesperado</title>
</head>
<body>
    <h1>Ocorreu um Erro!</h1>
    <p>Desculpe, algo deu errado: {{ error }}.</p>
    <p>Por favor, tente novamente mais tarde ou entre em contato com o suporte.</p>
    <a href="{{ url_for('users.login') }}">Voltar para a Página Inicial</a>
</body>
</html>

templates/html.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Titulo Gamer</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&display=swap" rel="stylesheet">
</head>
<body>

    <h1 class="title">Titulo Gamer</h1>
    <div class="container">
        <h3>Nome = se é admin</h3>
        <ul>
            {% for user in users %}
                <li>
                    {{ user.nome }} = 
                    {% if user.admin %}
                        é o fodão
                    {% else %}
                        Não é o fodão
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>

<h2>Login</h2>
<form action="/pegar" method="POST">
    <label for="username">Usuário:</label><br>
    <input type="text" id="username" name="username" required><br><br>
    
    <label for="password">Senha:</label><br>
    <input type="password" id="password" name="password" required><br><br>
    
    <button type="submit">Entrar</button>
    <P>
        {% if aviso %}
            {{ aviso }}
        {% endif %}    
    </P>
</form>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <p class="{{ category }}">{{ message }}</p>
            {% endfor %}    
        {% endif %}
    {% endwith %}

</body>
</html>

templates/rotavip.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página VIP</title>
</head>
<body>
    <h1>Bem-vindo à Página VIP!</h1>
    <p>Acesso exclusivo para usuários VIP.</p>
    <p>Usuário logado: {{ session['username'] }}</p>
</body>
</html>